from django import forms
from core.models import Avaliacao, Bairro


class AvaliacaoForm(forms.ModelForm):
    # Lista completa de bairros de Salvador
    BAIRROS_CHOICES = [
        ('Acupe', 'Acupe'),
        ('Aeroporto', 'Aeroporto'),
        ('Águas Claras', 'Águas Claras'),
        ('Alto da Terezinha', 'Alto da Terezinha'),
        ('Alto das Pombas', 'Alto das Pombas'),
        ('Alto do Cabrito', 'Alto do Cabrito'),
        ('Alto do Coqueirinho', 'Alto do Coqueirinho'),
        ('Amaralina', 'Amaralina'),
        ('Areia Branca', 'Areia Branca'),
        ('Arenoso', 'Arenoso'),
        ('Arraial do Retiro', 'Arraial do Retiro'),
        ('Bairro da Paz', 'Bairro da Paz'),
        ('Baixa de Quintas', 'Baixa de Quintas'),
        ('Barbalho', 'Barbalho'),
        ('Barra', 'Barra'),
        ('Barreiras', 'Barreiras'),
        ('Barris', 'Barris'),
        ('Beiru/Tancredo Neves', 'Beiru/Tancredo Neves'),
        ('Boa Viagem', 'Boa Viagem'),
        ('Boa Vista de Brotas', 'Boa Vista de Brotas'),
        ('Boa Vista de São Caetano', 'Boa Vista de São Caetano'),
        ('Boca da Mata', 'Boca da Mata'),
        ('Boca do Rio', 'Boca do Rio'),
        ('Bom Juá', 'Bom Juá'),
        ('Bonfim', 'Bonfim'),
        ('Brotas', 'Brotas'),
        ('Cabula', 'Cabula'),
        ('Cabula VI', 'Cabula VI'),
        ('Caixa D´Água', 'Caixa D´Água'),
        ('Cajazeiras II', 'Cajazeiras II'),
        ('Cajazeiras IV', 'Cajazeiras IV'),
        ('Cajazeiras V', 'Cajazeiras V'),
        ('Cajazeiras VI', 'Cajazeiras VI'),
        ('Cajazeiras VII', 'Cajazeiras VII'),
        ('Cajazeiras VIII', 'Cajazeiras VIII'),
        ('Cajazeiras X', 'Cajazeiras X'),
        ('Cajazeiras XI', 'Cajazeiras XI'),
        ('Calabar', 'Calabar'),
        ('Calabetão', 'Calabetão'),
        ('Calçada', 'Calçada'),
        ('Caminho das Árvores', 'Caminho das Árvores'),
        ('Caminho de Areia', 'Caminho de Areia'),
        ('Campinas de Pirajá', 'Campinas de Pirajá'),
        ('Canabrava', 'Canabrava'),
        ('Candeal', 'Candeal'),
        ('Canela', 'Canela'),
        ('Capelinha', 'Capelinha'),
        ('Cassange', 'Cassange'),
        ('Castelo Branco', 'Castelo Branco'),
        ('Centro', 'Centro'),
        ('Chame-Chame', 'Chame-Chame'),
        ('Cidade Nova', 'Cidade Nova'),
        ('Colinas de Periperi', 'Colinas de Periperi'),
        ('Comércio', 'Comércio'),
        ('Cosme de Farias', 'Cosme de Farias'),
        ('Costa Azul', 'Costa Azul'),
        ('Coutos', 'Coutos'),
        ('Curuzu', 'Curuzu'),
        ('Dois de Julho', 'Dois de Julho'),
        ('Dom Avelar', 'Dom Avelar'),
        ('Doron', 'Doron'),
        ('Engenho Velho da Federação', 'Engenho Velho da Federação'),
        ('Engenho Velho de Brotas', 'Engenho Velho de Brotas'),
        ('Engomadeira', 'Engomadeira'),
        ('Fazenda Coutos', 'Fazenda Coutos'),
        ('Fazenda Grande do Retiro', 'Fazenda Grande do Retiro'),
        ('Fazenda Grande I', 'Fazenda Grande I'),
        ('Fazenda Grande II', 'Fazenda Grande II'),
        ('Fazenda Grande III', 'Fazenda Grande III'),
        ('Fazenda Grande IV', 'Fazenda Grande IV'),
        ('Federação', 'Federação'),
        ('Garcia', 'Garcia'),
        ('Graça', 'Graça'),
        ('Granjas Rurais Presidente Vargas', 'Granjas Rurais Presidente Vargas'),
        ('Horto Florestal', 'Horto Florestal'),
        ('IAPI', 'IAPI'),
        ('Imbuí', 'Imbuí'),
        ('Itacaranha', 'Itacaranha'),
        ('Itaigara', 'Itaigara'),
        ('Itapuã', 'Itapuã'),
        ('Itinga', 'Itinga'),
        ('Jaguaripe I', 'Jaguaripe I'),
        ('Jardim Armação', 'Jardim Armação'),
        ('Jardim Cajazeiras', 'Jardim Cajazeiras'),
        ('Jardim das Margaridas', 'Jardim das Margaridas'),
        ('Jardim Nova Esperança', 'Jardim Nova Esperança'),
        ('Jardim Santo Inácio', 'Jardim Santo Inácio'),
        ('Lapinha', 'Lapinha'),
        ('Liberdade', 'Liberdade'),
        ('Lobato', 'Lobato'),
        ('Luiz Anselmo', 'Luiz Anselmo'),
        ('Macaúbas', 'Macaúbas'),
        ('Mangueira', 'Mangueira'),
        ('Marechal Rondon', 'Marechal Rondon'),
        ('Massaranduba', 'Massaranduba'),
        ('Mata Escura', 'Mata Escura'),
        ('Matatu', 'Matatu'),
        ('Mirantes de Periperi', 'Mirantes de Periperi'),
        ('Monte Serrat', 'Monte Serrat'),
        ('Moradas da Lagoa', 'Moradas da Lagoa'),
        ('Mussurunga', 'Mussurunga'),
        ('Narandiba', 'Narandiba'),
        ('Nazaré', 'Nazaré'),
        ('Nordeste de Amaralina', 'Nordeste de Amaralina'),
        ('Nova Brasília', 'Nova Brasília'),
        ('Nova Constituinte', 'Nova Constituinte'),
        ('Nova Esperança', 'Nova Esperança'),
        ('Nova Sussuarana', 'Nova Sussuarana'),
        ('Novo Horizonte', 'Novo Horizonte'),
        ('Novo Marotinho', 'Novo Marotinho'),
        ('Ondina', 'Ondina'),
        ('Palestina', 'Palestina'),
        ('Paripe', 'Paripe'),
        ('Patamares', 'Patamares'),
        ('Pau da Lima', 'Pau da Lima'),
        ('Pau Miúdo', 'Pau Miúdo'),
        ('Pelourinho', 'Pelourinho'),
        ('Periperi', 'Periperi'),
        ('Pernambués', 'Pernambués'),
        ('Pero Vaz', 'Pero Vaz'),
        ('Piatã', 'Piatã'),
        ('Pirajá', 'Pirajá'),
        ('Pituaçu', 'Pituaçu'),
        ('Pituba', 'Pituba'),
        ('Plataforma', 'Plataforma'),
        ('Porto Seco Pirajá', 'Porto Seco Pirajá'),
        ('Praia Grande', 'Praia Grande'),
        ('Resgate', 'Resgate'),
        ('Retiro', 'Retiro'),
        ('Ribeira', 'Ribeira'),
        ('Rio Sena', 'Rio Sena'),
        ('Rio Vermelho', 'Rio Vermelho'),
        ('Roma', 'Roma'),
        ('Saboeiro', 'Saboeiro'),
        ('Santa Cruz', 'Santa Cruz'),
        ('Santa Luzia', 'Santa Luzia'),
        ('Santa Mônica', 'Santa Mônica'),
        ('Santo Agostinho', 'Santo Agostinho'),
        ('Santo Antônio', 'Santo Antônio'),
        ('São Caetano', 'São Caetano'),
        ('São Cristóvão', 'São Cristóvão'),
        ('São Gonçalo', 'São Gonçalo'),
        ('São João do Cabrito', 'São João do Cabrito'),
        ('São Marcos', 'São Marcos'),
        ('São Rafael', 'São Rafael'),
        ('São Tomé', 'São Tomé'),
        ('Saramandaia', 'Saramandaia'),
        ('Saúde', 'Saúde'),
        ('Sete de Abril', 'Sete de Abril'),
        ('Stella Maris', 'Stella Maris'),
        ('STIEP', 'STIEP'),
        ('Sussuarana', 'Sussuarana'),
        ('Tororó', 'Tororó'),
        ('Trobogy', 'Trobogy'),
        ('Uruguai', 'Uruguai'),
        ('Vale das Pedrinhas', 'Vale das Pedrinhas'),
        ('Vale dos Lagos', 'Vale dos Lagos'),
        ('Valéria', 'Valéria'),
        ('Vila Canária', 'Vila Canária'),
        ('Vila Laura', 'Vila Laura'),
        ('Vila Ruy Barbosa/Jardim Cruzeiro', 'Vila Ruy Barbosa/Jardim Cruzeiro'),
        ('Vitória', 'Vitória'),
        ('Vista Alegre', 'Vista Alegre'),
    ]

    bairro = forms.ChoiceField(
        choices=BAIRROS_CHOICES,
        widget=forms.Select(attrs={
            'class': 'form-select',
            'data-live-search': 'true',
            'data-style': 'btn-outline-secondary',
            'title': 'Selecione um bairro'
        })
    )

    NOTA_CHOICES = [(i, str(i)) for i in range(1, 11)]

    nota = forms.ChoiceField(
        choices=NOTA_CHOICES,
        widget=forms.RadioSelect(attrs={
            'class': 'form-check-input nota-radio'
        }),
        initial=5  # Valor padrão
    )

    comentario = forms.CharField(
        required=False,
        widget=forms.Textarea(attrs={
            'class': 'form-control',
            'rows': 4,
            'placeholder': 'Deixe seu comentário sobre o bairro'
        })
    )

    class Meta:
        model = Avaliacao
        # Removendo 'bairro' daqui pois já foi definido acima
        fields = ['nota', 'comentario']
